FastFoodWebsite/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FastFoodWebsite.Models;
using FastFoodWebsite.Services;
namespace FastFoodWebsite.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        AdminService adminService = new AdminService();
        DB_FASTFOODDataContext db = new DB_FASTFOODDataContext();
        public ActionResult Index()
        {
            var orderList = db.ORDERDETAILs.ToList();
            return View(orderList);
        }
        public ActionResult ViewProduct()
        {
            try
            {

                ViewData["Err"] = TempData["Err"];
                List<Admin_Product> p = adminService.ExcuteSQL();
                return View(p);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
        public ActionResult AddProduct()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddProduct(Admin_Product product)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    adminService.AddSql(product.productName, product.productDescription, product.price, product.images, product.CreatedDate, product.productTypeID);
                    return RedirectToAction("ViewProduct");
                }
                else
                {
                    return View();
                }
            } catch (Exception ex)
            {
                return Content(ex.Message);
            }

        }

        public ActionResult DeleteProduct(int id)
        {
            try
            {
                if(!adminService.checkProductInCart(id))
                {
                    adminService.DeleteSql(id);
                    return RedirectToAction("ViewProduct");
                }   else
                {
                    TempData["Err"] = "Hiện tại chưa xoá được sản phẩm";
                    return RedirectToAction("ViewProduct");
                }    
               
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }

        public ActionResult UpdateProduct(int id)
        {
            Admin_Product p_ID = adminService.getProductByID(id);
            return View(p_ID);
        }
        [HttpPost]
        public ActionResult UpdateProduct(Admin_Product product)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    adminService.updateSql(product.productID, product.productName, product.productDescription, product.price, product.images, product.UpdatedDate, product.productTypeID);
                    return RedirectToAction("ViewProduct");
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }

        }


        public ActionResult Customers()
        {
            return View();
        }

        public ActionResult ResetPassword()
        {
            USER currentUser = Session["user"] as USER;
            User user = adminService.getUserByID(currentUser.USERID);
            return View(user);
        }
        [HttpPost]
        public ActionResult ResetPassword(User u)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    adminService.updatePassword(u.UserId, u.fullName, u.phone, u.email, u.password, u.confirmPassword, u.UpdatedDate, u.roleID);
                    return View();// để tạm, cho hiện lên cập nhật thành công
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
    }
}

FastFoodWebsite/Controllers/ProductController.cs
using FastFoodWebsite.Models;
using FastFoodWebsite.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FastFoodWebsite.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        DB_FASTFOODDataContext db = new DB_FASTFOODDataContext();

        public static int ITEM_SIZE = 3;

        public ActionResult MenuPartial(int pageNo = 1)
        {
            var product = db.PRODUCTs.ToList();

            return View(product);
            //    var allProducts = db.PRODUCTs.ToList();

            //    int pageSize = (int) allProducts.Count / ITEM_SIZE; // 2
            //    // page 1 => skip 0
            //    // page 2 => skip 3
            //    int skip = (pageNo - 1) * ITEM_SIZE;

            //    var product = db.PRODUCTs.Skip(skip).Take(ITEM_SIZE).ToList();

            //    ViewBag.pageSize = pageSize;
            //    return View(product);
        }
        public ActionResult Menu(int pageNo = 1)
        {
            int totalProduct = db.PRODUCTs.Count();

            int pageSize = (int)Math.Ceiling((double)totalProduct / ITEM_SIZE); // 2
            // page 1 => skip 0
            // page 2 => skip 3
            int skip = (pageNo - 1) * ITEM_SIZE;

            var product = db.PRODUCTs.Skip(skip).Take(ITEM_SIZE).ToList();

            ViewBag.pageSize = pageSize;
             ViewBag.currentPage = pageNo;

            return View(product);

        }
        public ActionResult DetailProduct(int id)
        {
            PRODUCT p = db.PRODUCTs.Single(ma => ma.PRODUCTID == id);
            return View(p);
        }
       
    }
}

FastFoodWebsite/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css" />
    <link rel="stylesheet" href="~/Content/login.css" />
    <link rel="stylesheet" href="~/Content/menucateory.css" />
    <link rel="stylesheet" href="~/Content/AboutUsCss.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">

</head>
<body>
    <header>
        <nav class="navlist">
            <div class="logo">
                <img src="~/Content/img/logo.png">
            </div>

            <ul>
                <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li><a href="@Url.Action("Menu", "Product")">Menu</a></li>
                @*<li><a href="#Review">Review</a></li>*@
                <li><a href="@Url.Action("AboutUs", "Home")">About Us</a></li>
                <li><a href="@Url.Action("Contact", "Home")">Contact</a></li>
            </ul>

            <div class="icon">
                @*<a><i class='bx bx-search-alt-2'></i></a>*@
                @if (Session["user"] != null)
                {
                    <a href="@Url.Action("ViewAccount", "Account")"><i class='bx bx-user-circle'></i></a>

                }
                else
                {
                    <a href="@Url.Action("LogIn", "Account")"><i class='bx bx-user-circle'></i></a>

                }
                @if (Session["user"] != null)
                {
                    <a href="@Url.Action("ViewCart", "Cart")"><i class='bx bx-cart'></i></a>

                }
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    <footer>

        <div class="footer_main">

            <div class="footer_tag">

                <h3>Location</h3>
                <p>Viet Nam</p>
                <p>Korea</p>
                <p>Japan</p>
                <p>USA</p>
                <p>China</p>
            </div>

            <div class="footer_tag">

                <h3>Quick Link</h3>
                <p>Home</p>
                <p>About</p>
                <p>Menu</p>
                <p>Gallery</p>
                <p>Order</p>

            </div>

            <div class="footer_tag">

                <h3>Contact</h3>
                <p>+84 38 9420 206</p>
                <p>+84 12 5768 456</p>
                <p>fengdinh@gmail.com</p>
                <p>tuyetchinh20042003@gmail.com</p>
            </div>

            <div class="footer_tag">

                <h3>Our Services</h3>
                <p>Fast Delivery</p>
                <p>Easy Payments</p>
                <p>24 x 7 Service</p>

            </div>

            <div class="footer_tag">

                <h3>Follows</h3>
                <i class="fa-brands fa-facebook-f"></i>
                <i class="fa-brands fa-twitter"></i>
                <i class="fa-brands fa-instagram"></i>
                <i class="fa-brands fa-linkedin-in"></i>

            </div>

        </div>

        <p class="end">Design by<span>Đinh Thị Tuyết Chinh</span></p>

    </footer>

    <script src="~/Scripts/bootstrap.esm.min.js" ></script>
    <script src="~/Scripts/bootstrap.js" ></script>
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

FastFoodWebsite/Views/Shared/_LayoutPageAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/AdminCss/AdminLayout.css" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="@Url.Content("~/Content/AdminCss/AdminProduct.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/AdminCss/AdminIndex.css")" />


</head>
<body>
    <div class="containerAdmin">
        <div class="navAdmin">
            <ul>
                <li>
                    <a href="#">
                        <span class="icon"><i class='bx bx-user-circle'></i></span>
                        <span class="title">Brand Name</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Admin")">
                        <span class="icon"><i class='bx bx-home'></i></span>
                        <span class="title">Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("ViewProduct", "Admin")">
                        <span class="icon"><i class='bx bx-food-menu'></i></span>
                        <span class="title">Products</span>
                    </a>
                </li>
                @*<li>
                    <a href="@Url.Action("Customers", "Admin")">
                        <span class="icon"><i class='bx bxs-user-account'></i></span>
                        <span class="title">Customers</span>
                    </a>
                </li>*@

                @*<li>
                    <a href="#">
                        <span class="icon"><i class='bx bx-help-circle'></i></span>
                        <span class="title">Help</span>
                    </a>
                </li>*@
                <li>
                    <a href="@Url.Action("ViewAccount", "Account")">
                        <span class="icon"><i class='bx bx-cog'></i></span>
                        <span class="title">Settings</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("ResetPassword", "Admin")">
                        <span class="icon"><i class='bx bx-lock-alt'></i></span>
                        <span class="title">Password</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("LogIn", "Account")">
                        <span class="icon"><i class='bx bx-log-out'></i></span>
                        <span class="title">Sign out</span>
                    </a>
                </li>
            </ul>
        </div>

        <!-- MAIN -->
        <div class="main">
            <div class="top-nav">
                <div class="toggle">
                    <i class='bx bx-menu'></i>
                </div>

                <div class="searchAdmin">
                    <label>
                        <input type="text" placeholder="Search here" />
                        <div class="icon-card"><i class='bx bx-search-alt-2'></i></div>
                    </label>
                </div>

                <div class="user">
                    <a href="@Url.Action("ViewAccount", "Account")">
                        <img src="~/Content/img/tuyetchinh.jpg" />
                    </a>
                </div>
            </div>

            <!-- card -->
            <div class="card-boxAdmin">
                <div class="cardAdmin">
                    <div>
                        <div class="numbers">1.504</div>
                        <div class="card-name">DailyViews</div>
                    </div>
                    <div class="icon-card"><ion-icon name="eye-outline"></ion-icon></div>
                </div>
                <div class="cardAdmin">
                    <div>
                        <div class="numbers">200</div>
                        <div class="card-name">Comments</div>
                    </div>
                    <div class="icon-card"><ion-icon name="chatbox-outline"></ion-icon></div>
                </div>
                <div class="cardAdmin">
                    <div>
                        <div class="numbers">100</div>
                        <div class="card-name">Sales</div>
                    </div>
                    <div class="icon-card"><i class='bx bx-cart'></i></div>
                </div>
                <div class="cardAdmin">
                    <div>
                        <div class="numbers">$25.987</div>
                        <div class="card-name">Earning</div>
                    </div>
                    <div class="icon-card"><ion-icon name="cash-outline"></ion-icon></div>
                </div>
            </div>
            <div>
                @RenderBody()
            </div>
        </div>

    </div>

    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>


</body>
</html>